### PR TITLE
minimal example to support question on vectorization

### PR DESCRIPTION
**Pull request by mbannert**

### CODE REVIEW

**Comment by fabiangehring** [comment]
Don't use a pattern like example 1. Use vectorization!

Both, example 2 and 3 will be way! faster than yours. Example 2 does not make use of the data.table package. Example 3 might therefore be slightly faster (but definitely unneeded microoptimization in this case!) Depending on personal preferences it might also be slightly clearer in terms of syntax . 

If you prefer working with dplyr you can easily modify the example for a forth one. 

My advise: Go with 2 and you'll be fine!

```
# Ex1
data(iris)
computePrice <- function(a,b,
                         spec,
                         VAT = .08){
  if(spec == "setosa"){
    tot <- (a+b)*1.10
  } else{
    tot <- (a*b)/2
  }
  tot*(1+VAT)
}

iris$Price1 <- apply(iris,1,function(x){
  computePrice(as.numeric(x["Sepal.Length"]),
               as.numeric(x["Petal.Length"]),
               x["Species"]) 
})
iris$Price 


# Ex2
VAT <- 0.08
setosa <- iris$Species == "setosa"
iris$Price2[setosa] <- 1.1 * (1 + VAT) * (iris[, "Sepal.Length"][setosa] + iris[, "Petal.Length"][setosa])
iris$Price2[!setosa] <- (1 + VAT) * (iris[, "Sepal.Length"][!setosa] * iris[, "Petal.Length"][!setosa])/2
iris$Price2 


# Ex3
library(data.table)
setDT(iris)

VAT <- 0.08
iris[Species == "setosa", Price3 := 1.1 * (1 + VAT) * (Sepal.Length + Petal.Length)]
iris[Species != "setosa", Price3 := (1 + VAT) * (Sepal.Length * Petal.Length) / 2]
iris$Price3

```

**Comment by mbannert** [comment]
@fabiangehrig thanks for taking the time to write up better solutions. Do you have any general advice / good strategy to avoid loops / apply in custom functions and use vectorization instead? What do you do to stay vectorised in more complex setups? Are there some neat linear algebra tricks that you use often ?

**Comment by mmaechler** [comment]
Guys, that's great how you help each other before I even see it.  :+1: 
Since this has been a PR (pull request), could you _edit_ the pull request to also include at least example 2?

((I like solutions that don't need `data.table`.  Data.table is really a new R-like language implemented in R ... and I don't know much about that language.. but it does differ from R ... **and** it can be very fast ))

**Comment by mbannert** [comment]
@mmaechler @fabiangehring I added Fabian's example to this. In case we address microbenchmark today we might even want to look at home much faster it really is. I guess we will need some replications to really see the difference with this (tiny) size of the dataset. 

speaking of data.table: the same holds for dplyr + co, it's kind of its own universe within R. data.table is at least very similar to SQL. However, I left it out because the idea was really to talk about vectorization and strategies to think a bit more vectorized.

**Comment by mmaechler** [comment]
@mbannert re `dplyr` + "hadleyverse" (newly =: "tidyverse"):  You are right. It has its own vocabulary, but apart from the pipe, it's R's syntax,  whereas `data.table` introduces new syntax and very much redefines the meaning of `[` ... which so basic to the language.   .. never mind  Thanks for the Ex. now merging.

**Pull request merged**
